### ISSUE TITLE
Data for secondary market

### ISSUE THREAD

**Issue by mickovski** [mickovski/lendingclub#2]
1. We can download historical data from Lending Club website, but I think it is for primary market.
2. The only API we can get from Lending Club is for loans currently listed 
3. I found a website for trading platform of Lending Club, but they did not approve my account. Thus, I cannot get the data from the website (if the data exist)
4. I've never used Python before but Walter has done that before, but I could learn that.

**Comment by mickovski** [comment]
5. For the model, are we trying to predict expected default rate from variables such as dti, fico, interest rate, number of delinquent ...?

**Comment by mickovski** [comment]
6. I'll add Walter as a contributor.

**Comment by mickovski** [comment]
7. I'll let Walter say exactly which variables we plan to use for the model.

**Comment by bubblesort251** [comment]
I have a few thoughts.

1) I believe that there is a historical view for the API, which I will also look into for this next week.  We need a historical set of loans that includes the information Lending Club had at the time they issued the loan + the performance of the loan (i.e how many good payments they made, etc)
*This is priority 1*
2) Our target variable will 18th month performance.  So we'll make our own target like 1: if at the 18th month mark they have defaulted on the loan or they haven't made a payment in the past 6 months 0: otherwise (This definition can be tweaked, but that's the basic idea).  If you are trying to debug your code, feel free to use the expected default rate as your target variable
